### ISSUE TITLE
CONTRIBUTING.md references missing code of conduct and pull request template

### ISSUE THREAD

**Issue by filmaj** [adobe/UST-Install-Scripts#1]
Both links lead to 404 pages.

Should we add these docs, or should we remove references to them from the contribution guidelines?

**Comment by vossen-adobe** [comment]
Thanks for pointing that out! I added the missing docs - unless there is a more accepted way I should be adding that content per adobe, I'll go ahead and close this issue

**Comment by filmaj** [comment]
Thank you, looks great!
