### ISSUE TITLE
 Add support for OAuth Credentials

### ISSUE THREAD

**Issue by CorstianB** [adobe/UST-Install-Scripts#11]
Description
The User Sync Tool had been updated to support the new OAuth Server-to-Server credential.

Expected behavior
Support for OAuth so we can migrate away from JWT

**Comment by adorton-adobe** [comment]
The feature is currently in pre-release. The UST installer doesn't work with pre-releases.

See https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v2.10.0rc2

**Comment by CorstianB** [comment]
It seems like support for oath was added in v2.9.0?
https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v2.9.0

**Comment by CorstianB** [comment]
@adorton-adobe
