### ISSUE TITLE
Authentication Proxy

### ISSUE THREAD

**Issue by norihiroGitHub** [adobe/UST-Install-Scripts#4]
If the customer has Authentication Proxy, is there any tips to type ID & password in this script?

**Comment by vossen-adobe** [comment]
The windows version no longer depends on internet access - it's now a bundled MSI: https://github.com/adobe/UST-Install-Scripts/releases/latest

I'll mark this as a possible enhancement for the linux scripts.  This might be a good opportunity to add an HTTPS_PROXY option during setup for the sync tool.

**Comment by norihiroGitHub** [comment]
This is the greatest installer and to complete UST environment.
I should ask Japanese version of the installer. If you give me the list of test, I will translate them in Japanese and back to you.
