### ISSUE TITLE
while installation getting pop up to restart system on windows

### ISSUE THREAD

**Issue by shasibhusanJena** [adobe/UST-Install-Scripts#8]
wanted to set up latest build on local. while I install, got some warning to restart after installation system restarted.   

version name :- v2.6

<img width="807" alt="ust 2 3 setup" src="https://user-images.githubusercontent.com/23555157/51253989-f0c1df80-19c5-11e9-9c36-b659c4bc147b.PNG">
<img width="894" alt="ust latest release" src="https://user-images.githubusercontent.com/23555157/51253991-f0c1df80-19c5-11e9-9e01-5abc8936239e.PNG">
<img width="812" alt="image three after install got this warning" src="https://user-images.githubusercontent.com/23555157/51253992-f15a7600-19c5-11e9-8ac4-faf01dc14a1d.PNG">

**Comment by vossen-adobe** [comment]
Interesting - we've never seen this before, it could be specific to that machine for some reason.  Did you install python with the installer, and if so which version? And  which windows version?

Also, if you could generate an MSI log that would be helpful:

msiexec /i AdobeUSTSetup.msi /l*v

**Comment by vossen-adobe** [comment]
Actually, this might be because you are installing into the directory containing the installer - could you move it outside and try?

**Comment by vossen-adobe** [comment]
I have tested this and that seems to be the case. It's because the installer wipes the install directory if it exists prior to installation (this is intentional to keep things clean).  If the installer exists there, it can't remove itself, so it's prompting you to restart.  Please let me know if this resolves the issue and I'll close the thread!

**Comment by shasibhusanJena** [comment]
> I have tested this and that seems to be the case. It's because the installer wipes the install directory if it exists prior to installation (this is intentional to keep things clean). If the installer exists there, it can't remove itself, so it's prompting you to restart. Please let me know if this resolves the issue and I'll close the thread!

oh ok, it means its a known behavior. I was worried as it is prompting me to restart and did not allow me to install.  @janssenda-adobe  you can verify and close the issue.

**Comment by vossen-adobe** [comment]
Thanks Shasi! Closed.
